import React, { useState, useEffect, useCallback } from "react";

const PAGE_SIZE = 10;
// const API_BASE_URL = "http://localhost:8080/api/salesforce";

// const API_BASE_URL = window.location.hostname === "localhost"
//   ? "http://localhost:8080/api/salesforce"
//   : "https://onrender.com";

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL ||
  "http://localhost:8080";

const SALESFORCE_API_URL =
  `${API_BASE_URL}/api/salesforce`;
const OBJECT_FIELDS = {
  Account: ["Name", "Phone", "Industry", "Website", "Type"],

  Opportunity: ["Name", "StageName", "Amount", "CloseDate", "Type"],

  Lead: [
    "FirstName",
    "LastName",
    "Company",
    "Status",
    "Email",
    "Phone",
  ],

  Contact: [
    "FirstName",
    "LastName",
    "Email",
    "Phone",
    "Department",
  ],

  Case: [
    "CaseNumber",
    "Subject",
    "Status",
    "Priority",
    "Origin",
  ],
};

export default function Dashboard() {
  const [selectedObject, setSelectedObject] = useState("Account");
  const [records, setRecords] = useState([]);

  // Pagination
  const [offset, setOffset] = useState(0);
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  // Modal
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingRecord, setEditingRecord] = useState(null);
  const [formData, setFormData] = useState({});

  /*
   * ==========================================
   * FETCH RECORDS
   * ==========================================
   *
   * Fetch exactly one page from Salesforce.
   *
   * offset = 0  -> records 1-10
   * offset = 10 -> records 11-20
   * offset = 20 -> records 21-30
   */
  const fetchRecords = useCallback(
    async (objectName, currentOffset) => {
      setLoading(true);

      try {
        const response = await fetch(
          `${API_BASE_URL}/${objectName}?offset=${currentOffset}&limit=${PAGE_SIZE}`
        );

        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(
            `HTTP ${response.status}: ${errorText || "Unable to fetch records"}`
          );
        }

        const data = await response.json();

        const newRecords = data.records || [];

        console.log(
          `Fetched ${newRecords.length} ${objectName} records at offset ${currentOffset}`
        );

        // Replace current table data with latest Salesforce data.
        setRecords(newRecords);

        // If fewer than PAGE_SIZE records are returned,
        // there is no next page.
        setHasMore(newRecords.length === PAGE_SIZE);
      } catch (error) {
        console.error("Error fetching Salesforce records:", error);

        setRecords([]);
        setHasMore(false);
      } finally {
        setLoading(false);
      }
    },
    []
  );

  /*
   * ==========================================
   * INITIAL LOAD / OBJECT / PAGINATION
   * ==========================================
   */
  useEffect(() => {
    fetchRecords(selectedObject, offset);
  }, [selectedObject, offset, fetchRecords]);

  /*
   * ==========================================
   * CHANGE SALESFORCE OBJECT
   * ==========================================
   */
  const handleObjectChange = (e) => {
    const newObject = e.target.value;

    setSelectedObject(newObject);

    // Always start from first page when changing object.
    setOffset(0);
  };

  /*
   * ==========================================
   * NEXT PAGE
   * ==========================================
   */
  const handleNextPage = () => {
    if (!loading && hasMore) {
      setOffset((previousOffset) => previousOffset + PAGE_SIZE);
    }
  };

  /*
   * ==========================================
   * PREVIOUS PAGE
   * ==========================================
   */
  const handlePrevPage = () => {
    if (!loading && offset > 0) {
      setOffset((previousOffset) =>
        Math.max(0, previousOffset - PAGE_SIZE)
      );
    }
  };

  /*
   * ==========================================
   * CREATE MODAL
   * ==========================================
   */
  const handleOpenCreate = () => {
    setEditingRecord(null);

    const initialForm = {};

    OBJECT_FIELDS[selectedObject].forEach((field) => {
      // CaseNumber is generated by Salesforce.
      if (field === "CaseNumber") {
        return;
      }

      initialForm[field] = "";
    });

    setFormData(initialForm);
    setIsModalOpen(true);
  };

  /*
   * ==========================================
   * EDIT MODAL
   * ==========================================
   */
  const handleOpenEdit = (record) => {
    setEditingRecord(record);

    const currentForm = {};

    OBJECT_FIELDS[selectedObject].forEach((field) => {
      /*
       * CaseNumber is generated by Salesforce
       * and is read-only.
       *
       * Do NOT put it into the edit payload.
       */
      if (field === "CaseNumber") {
        return;
      }

      currentForm[field] = record[field] ?? "";
    });

    setFormData(currentForm);
    setIsModalOpen(true);
  };

  /*
   * ==========================================
   * FORM INPUT
   * ==========================================
   */
  const handleInputChange = (e, field) => {
    setFormData((previousData) => ({
      ...previousData,
      [field]: e.target.value,
    }));
  };

  /*
   * ==========================================
   * CLOSE MODAL
   * ==========================================
   */
  const handleCloseModal = () => {
    setIsModalOpen(false);
    setEditingRecord(null);
    setFormData({});
  };

  /*
   * ==========================================
   * FORMAT SALESFORCE ERROR
   * ==========================================
   */
  const getSalesforceErrorMessage = (responseText) => {
    if (!responseText) {
      return "Salesforce returned an empty error response.";
    }

    let errorMessage = responseText;

    try {
      const errorData = JSON.parse(responseText);

      /*
       * Salesforce REST API normally returns:
       *
       * [
       *   {
       *     "message": "...",
       *     "errorCode": "...",
       *     "fields": []
       *   }
       * ]
       */
      if (Array.isArray(errorData)) {
        errorMessage = errorData
          .map((error) => {
            const message =
              error.message || "Unknown Salesforce error";

            const code = error.errorCode
              ? ` [${error.errorCode}]`
              : "";

            const fields =
              error.fields &&
              error.fields.length > 0
                ? ` Fields: ${error.fields.join(", ")}`
                : "";

            return `${message}${code}${fields}`;
          })
          .join("\n");
      } else if (errorData.message) {
        errorMessage = errorData.message;
      } else if (errorData.error) {
        errorMessage =
          typeof errorData.error === "string"
            ? errorData.error
            : JSON.stringify(errorData.error);
      }
    } catch (error) {
      // Response was not JSON.
      // Keep original response text.
    }

    return errorMessage;
  };

  /*
   * ==========================================
   * CREATE / UPDATE
   * ==========================================
   */
  const handleSubmitForm = async (e) => {
    e.preventDefault();

    const isEditing = Boolean(editingRecord);

    const url = isEditing
      ? `${API_BASE_URL}/${selectedObject}/${editingRecord.Id}`
      : `${API_BASE_URL}/${selectedObject}`;

    const method = isEditing ? "PATCH" : "POST";

    /*
     * Create a clean payload.
     *
     * Never send:
     * - Id
     * - CaseNumber
     *
     * Both are read-only for our form operations.
     */
    const payload = { ...formData };

    delete payload.Id;
    delete payload.CaseNumber;

    /*
     * Do not send empty strings.
     */
    Object.keys(payload).forEach((key) => {
      if (
        payload[key] === "" ||
        payload[key] === null ||
        payload[key] === undefined
      ) {
        delete payload[key];
      }
    });

    console.log("=================================");
    console.log("Salesforce operation:", method);
    console.log("Salesforce object:", selectedObject);
    console.log("Record ID:", editingRecord?.Id);
    console.log("Payload:", payload);
    console.log("Current offset:", offset);
    console.log("=================================");

    try {
      const response = await fetch(url, {
        method,
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify(payload),
      });

      /*
       * ALWAYS read the response.
       *
       * Salesforce may return useful error details.
       */
      const responseText = await response.text();

      console.log(
        "Salesforce HTTP status:",
        response.status
      );

      console.log(
        "Salesforce response:",
        responseText
      );

      /*
       * ==========================================
       * ERROR
       * ==========================================
       */
      if (!response.ok) {
        const errorMessage =
          getSalesforceErrorMessage(responseText);

        alert(
          `Salesforce rejected the ${
            method === "PATCH"
              ? "update"
              : "operation"
          }:\n\n${errorMessage}`
        );

        return;
      }

      /*
       * ==========================================
       * SUCCESS
       * ==========================================
       */

      alert(
        isEditing
          ? `${selectedObject} updated successfully.`
          : `${selectedObject} created successfully.`
      );

      /*
       * Close modal.
       */
      handleCloseModal();

      /*
       * IMPORTANT:
       *
       * Fetch using the CURRENT offset.
       *
       * Do NOT use:
       *
       * fetchRecords()
       *
       * Do NOT reset offset to 0.
       *
       * This keeps the user on the same page.
       */
      await fetchRecords(
        selectedObject,
        offset
      );
    } catch (error) {
      console.error(
        "Error committing record mutation:",
        error
      );

      alert(
        `Unable to communicate with Salesforce.\n\n${error.message}`
      );
    }
  };

  /*
   * ==========================================
   * DELETE RECORD
   * ==========================================
   */
  const handleDelete = async (recordId) => {
    const confirmed = window.confirm(
      "Are you sure you want to permanently delete this record?"
    );

    if (!confirmed) {
      return;
    }

    console.log("=================================");
    console.log("Salesforce DELETE");
    console.log("Object:", selectedObject);
    console.log("Record ID:", recordId);
    console.log("Current offset:", offset);
    console.log("=================================");

    try {
      const response = await fetch(
        `${API_BASE_URL}/${selectedObject}/${recordId}`,
        {
          method: "DELETE",
          headers: {
            Accept: "application/json",
          },
        }
      );

      /*
       * ALWAYS read the response.
       */
      const responseText = await response.text();

      console.log(
        "Salesforce DELETE status:",
        response.status
      );

      console.log(
        "Salesforce DELETE response:",
        responseText
      );

      /*
       * ==========================================
       * DELETE ERROR
       * ==========================================
       */
      if (!response.ok) {
        const errorMessage =
          getSalesforceErrorMessage(responseText);

        alert(
          `Salesforce rejected the delete:\n\n${errorMessage}`
        );

        return;
      }

      /*
       * ==========================================
       * DELETE SUCCESS
       * ==========================================
       */

      alert("Record deleted successfully.");

      /*
       * If this was the last record on a page other
       * than page 1, move to the previous page.
       *
       * Example:
       * page 2 has only one record
       * delete it
       * -> go back to page 1
       */
      if (records.length === 1 && offset > 0) {
        setOffset((previousOffset) =>
          Math.max(
            0,
            previousOffset - PAGE_SIZE
          )
        );
      } else {
        /*
         * Otherwise reload the CURRENT page.
         */
        await fetchRecords(
          selectedObject,
          offset
        );
      }
    } catch (error) {
      console.error(
        "Error deleting Salesforce record:",
        error
      );

      alert(
        `Unable to communicate with Salesforce.\n\n${error.message}`
      );
    }
  };

  /*
   * ==========================================
   * DISPLAYED RECORD NUMBERS
   * ==========================================
   */
  const firstRecordNumber =
    records.length > 0
      ? offset + 1
      : 0;

  const lastRecordNumber =
    offset + records.length;

  /*
   * ==========================================
   * RENDER
   * ==========================================
   */
  return (
    <div
      style={{
        padding: "32px",
        fontFamily: "sans-serif",
        color: "#333",
        backgroundColor: "#fff",
        minHeight: "100vh",
        boxSizing: "border-box",
        width: "100%",
        textAlign: "left",
      }}
    >
      {/* ======================================
          HEADER
          ====================================== */}

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "24px",
          borderBottom: "1px solid #eee",
          paddingBottom: "12px",
        }}
      >
        <h2
          style={{
            margin: 0,
            color: "#222",
            fontSize: "24px",
            fontWeight: "bold",
          }}
        >
          Salesforce Corporate Records
          Management Dashboard
        </h2>

        <button
          onClick={() => {
            window.location.href = "/";
          }}
          style={{
            padding: "8px 16px",
            backgroundColor: "#d9534f",
            color: "#fff",
            border: "none",
            borderRadius: "4px",
            cursor: "pointer",
            fontWeight: "bold",
          }}
        >
          Disconnect
        </button>
      </div>

      {/* ======================================
          CONTROL PANEL
          ====================================== */}

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "24px",
          padding: "16px",
          backgroundColor: "#f4f6f9",
          borderRadius: "6px",
        }}
      >
        <div>
          <label
            style={{
              marginRight: "12px",
              fontWeight: "bold",
              fontSize: "16px",
            }}
          >
            Select Standard Object:
          </label>

          <select
            value={selectedObject}
            onChange={handleObjectChange}
            style={{
              padding: "10px 16px",
              borderRadius: "4px",
              border: "1px solid #ccc",
              fontSize: "16px",
              minWidth: "200px",
              backgroundColor: "#fff",
              color: "#333",
            }}
          >
            {Object.keys(OBJECT_FIELDS).map(
              (objectName) => (
                <option
                  key={objectName}
                  value={objectName}
                >
                  {objectName}
                </option>
              )
            )}
          </select>
        </div>

        <button
          onClick={handleOpenCreate}
          style={{
            padding: "10px 20px",
            backgroundColor: "#4bca81",
            color: "#fff",
            border: "none",
            borderRadius: "4px",
            cursor: "pointer",
            fontWeight: "bold",
            fontSize: "15px",
          }}
        >
          + Create New {selectedObject}
        </button>
      </div>

      {/* ======================================
          TABLE
          ====================================== */}

      <div
        style={{
          maxHeight: "500px",
          overflowY: "auto",
          border: "1px solid #e0e0e0",
          borderRadius: "4px",
          width: "100%",
        }}
      >
        <table
          style={{
            width: "100%",
            borderCollapse: "collapse",
            backgroundColor: "#fff",
          }}
        >
          <thead
            style={{
              backgroundColor: "#f8f9fa",
              position: "sticky",
              top: 0,
              zIndex: 1,
            }}
          >
            <tr>
              {OBJECT_FIELDS[selectedObject].map(
                (field) => (
                  <th
                    key={field}
                    style={{
                      padding: "14px",
                      borderBottom:
                        "2px solid #dee2e6",
                      textAlign: "left",
                      color: "#333",
                      fontWeight: "bold",
                    }}
                  >
                    {field}
                  </th>
                )
              )}

              <th
                style={{
                  padding: "14px",
                  borderBottom:
                    "2px solid #dee2e6",
                  textAlign: "left",
                  color: "#333",
                  fontWeight: "bold",
                }}
              >
                Operations
              </th>
            </tr>
          </thead>

          <tbody>
            {loading ? (
              <tr>
                <td
                  colSpan={
                    OBJECT_FIELDS[selectedObject]
                      .length + 1
                  }
                  style={{
                    textAlign: "center",
                    padding: "30px",
                    color: "#0070d2",
                    fontWeight: "bold",
                  }}
                >
                  Syncing live entries...
                </td>
              </tr>
            ) : records.length === 0 ? (
              <tr>
                <td
                  colSpan={
                    OBJECT_FIELDS[selectedObject]
                      .length + 1
                  }
                  style={{
                    textAlign: "center",
                    padding: "30px",
                    color: "#777",
                  }}
                >
                  No records found.
                </td>
              </tr>
            ) : (
              records.map((record, index) => (
                <tr
                  key={record.Id || index}
                  style={{
                    borderBottom:
                      "1px solid #eceeef",
                    backgroundColor: "#fff",
                  }}
                >
                  {OBJECT_FIELDS[
                    selectedObject
                  ].map((field) => (
                    <td
                      key={field}
                      style={{
                        padding: "14px",
                        color: "#444",
                        textAlign: "left",
                      }}
                    >
                      {typeof record[field] ===
                        "object" &&
                      record[field] !== null
                        ? record[field]?.Name ||
                          "—"
                        : String(
                            record[field] ?? "—"
                          )}
                    </td>
                  ))}

                  <td
                    style={{
                      padding: "14px",
                      whiteSpace: "nowrap",
                    }}
                  >
                    {/* EDIT */}

                    <button
                      onClick={() =>
                        handleOpenEdit(record)
                      }
                      style={{
                        marginRight: "8px",
                        padding: "6px 12px",
                        border:
                          "1px solid #0070d2",
                        borderRadius: "4px",
                        color: "#0070d2",
                        backgroundColor: "#fff",
                        cursor: "pointer",
                        fontWeight: "600",
                      }}
                    >
                      Edit
                    </button>

                    {/* DELETE */}

                    <button
                      onClick={() =>
                        handleDelete(record.Id)
                      }
                      style={{
                        padding: "6px 12px",
                        border:
                          "1px solid #d9534f",
                        borderRadius: "4px",
                        color: "#d9534f",
                        backgroundColor: "#fff",
                        cursor: "pointer",
                        fontWeight: "600",
                      }}
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* ======================================
          PAGINATION
          ====================================== */}

      <div
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "16px",
          marginTop: "24px",
        }}
      >
        {/* PREVIOUS */}

        <button
          onClick={handlePrevPage}
          disabled={
            offset === 0 || loading
          }
          style={{
            padding: "10px 20px",
            backgroundColor:
              offset === 0
                ? "#e0e0e0"
                : "#fff",
            color:
              offset === 0
                ? "#999"
                : "#0070d2",
            border: "1px solid #ccc",
            borderRadius: "4px",
            cursor:
              offset === 0 || loading
                ? "not-allowed"
                : "pointer",
            fontWeight: "bold",
          }}
        >
          ← Previous 10
        </button>

        {/* PAGE INFORMATION */}

        <span
          style={{
            fontWeight: "bold",
            color: "#555",
            minWidth: "180px",
            textAlign: "center",
          }}
        >
          Showing Records{" "}
          {firstRecordNumber} -{" "}
          {lastRecordNumber}
        </span>

        {/* NEXT */}

        <button
          onClick={handleNextPage}
          disabled={
            !hasMore || loading
          }
          style={{
            padding: "10px 20px",
            backgroundColor:
              !hasMore
                ? "#e0e0e0"
                : "#0070d2",
            color:
              !hasMore
                ? "#999"
                : "#fff",
            border: "none",
            borderRadius: "4px",
            cursor:
              !hasMore || loading
                ? "not-allowed"
                : "pointer",
            fontWeight: "bold",
          }}
        >
          Next 10 →
        </button>
      </div>

      {/* ======================================
          MODAL
          ====================================== */}

      {isModalOpen && (
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            backgroundColor:
              "rgba(0,0,0,0.5)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 100,
          }}
        >
          <div
            style={{
              backgroundColor: "#fff",
              padding: "32px",
              borderRadius: "8px",
              width: "450px",
              maxWidth: "90%",
              boxShadow:
                "0 4px 20px rgba(0,0,0,0.2)",
            }}
          >
            <h3
              style={{
                marginTop: 0,
                marginBottom: "20px",
                color: "#111",
                fontWeight: "bold",
              }}
            >
              {editingRecord
                ? `Modify ${selectedObject}`
                : `Add New ${selectedObject}`}
            </h3>

            <form
              onSubmit={handleSubmitForm}
            >
              <div
                style={{
                  maxHeight: "350px",
                  overflowY: "auto",
                  paddingRight: "4px",
                }}
              >
                {OBJECT_FIELDS[
                  selectedObject
                ].map((field) => {
                  /*
                   * CaseNumber is generated by
                   * Salesforce and is read-only.
                   */
                  if (
                    field === "CaseNumber"
                  ) {
                    return null;
                  }

                  return (
                    <div
                      key={field}
                      style={{
                        marginBottom: "16px",
                      }}
                    >
                      <label
                        style={{
                          display: "block",
                          marginBottom: "6px",
                          fontWeight: "bold",
                          color: "#333",
                        }}
                      >
                        {field}
                      </label>

                      <input
                        type={
                          field
                            .toLowerCase()
                            .includes("date")
                            ? "date"
                            : field
                                .toLowerCase()
                                .includes(
                                  "email"
                                )
                            ? "email"
                            : "text"
                        }
                        value={
                          formData[field] ||
                          ""
                        }
                        onChange={(e) =>
                          handleInputChange(
                            e,
                            field
                          )
                        }
                        required={
                          field === "Name" ||
                          field === "Subject" ||
                          field === "LastName" ||
                          (
                            selectedObject ===
                              "Lead" &&
                            field ===
                              "Company"
                          )
                        }
                        style={{
                          width: "100%",
                          padding: "10px",
                          borderRadius: "4px",
                          border:
                            "1px solid #ccc",
                          boxSizing:
                            "border-box",
                          backgroundColor:
                            "#fff",
                          color: "#333",
                        }}
                      />
                    </div>
                  );
                })}
              </div>

              {/* MODAL BUTTONS */}

              <div
                style={{
                  display: "flex",
                  justifyContent:
                    "flex-end",
                  marginTop: "24px",
                  borderTop:
                    "1px solid #eee",
                  paddingTop: "16px",
                }}
              >
                <button
                  type="button"
                  onClick={
                    handleCloseModal
                  }
                  style={{
                    marginRight: "12px",
                    padding: "10px 16px",
                    border:
                      "1px solid #aaa",
                    backgroundColor:
                      "#f8f9fa",
                    color: "#333",
                    borderRadius: "4px",
                    cursor: "pointer",
                    fontWeight: "bold",
                  }}
                >
                  Cancel
                </button>

                <button
                  type="submit"
                  style={{
                    padding: "10px 20px",
                    backgroundColor:
                      "#0070d2",
                    color: "#fff",
                    border: "none",
                    borderRadius: "4px",
                    cursor: "pointer",
                    fontWeight: "bold",
                  }}
                >
                  {editingRecord
                    ? "Save Changes"
                    : "Create Record"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
