# server.port=8080
# spring.application.name=salesforce-crud-backend

# # Production placeholders for the evaluator to fill out
# salesforce.client-id=${SALESFORCE_CLIENT_ID:YOUR_CONSUMER_KEY_PLACEHOLDER}
# salesforce.client-secret=${SALESFORCE_CLIENT_SECRET:YOUR_CONSUMER_SECRET_PLACEHOLDER}
# salesforce.redirect-uri=${SALESFORCE_REDIRECT_URI:http://localhost:8080/api/auth/callback}
# # salesforce.login-url=https://salesforce.com
# salesforce.login-url=https://login.salesforce.com
# frontend.url=${FRONTEND_URL:http://localhost:5173}

server.port=8080
spring.application.name=salesforce-crud-backend

salesforce.client-id=${SALESFORCE_CLIENT_ID:YOUR_CONSUMER_KEY_PLACEHOLDER}
salesforce.client-secret=${SALESFORCE_CLIENT_SECRET:YOUR_CONSUMER_SECRET_PLACEHOLDER}

salesforce.redirect-uri=${SALESFORCE_REDIRECT_URI:http://localhost:8080/api/auth/callback}

salesforce.login-url=https://login.salesforce.com

frontend.url=${FRONTEND_URL:http://localhost:5173}